// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/tasks": {
    params: {};
  };
  "/projects": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/tasks" | "/projects";
  };
  "pages/home.tsx": {
    id: "pages/home";
    page: "/";
  };
  "pages/dashboard/index.tsx": {
    id: "pages/dashboard/index";
    page: "/dashboard";
  };
  "pages/tasks/index.tsx": {
    id: "pages/tasks/index";
    page: "/tasks";
  };
  "pages/projects/index.tsx": {
    id: "pages/projects/index";
    page: "/projects";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/home": typeof import("./src/pages/home.tsx");
  "pages/dashboard/index": typeof import("./src/pages/dashboard/index.tsx");
  "pages/tasks/index": typeof import("./src/pages/tasks/index.tsx");
  "pages/projects/index": typeof import("./src/pages/projects/index.tsx");
};